# TensorFlow Basics

In [2]:
import tensorflow as tf

C:\Users\venkat\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
#this isa variable
zero = tf.Variable(0)

In [4]:
#This is a constant
one = tf.constant(1)

In [5]:
new_value = tf.add(zero,one)

In [6]:
#you can't update a constant
update = tf.assign(one,zero)

AttributeError: 'Tensor' object has no attribute 'assign'

In [7]:
#we can change values for constant
update = tf.assign(zero,new_value)

In [19]:
#need to call this initializer when there are varibles...not required when if we have only constants and placeholders
init_op = tf.global_variables_initializer()

In [23]:
#common sntax to create session, here we need not to close session
with tf.Session() as sess:
    sess.run(init_op)
    for _ in range(5):
        sess.run(update)
        print(sess.run(zero))

1
2
3
4
5


In [25]:
#other way to craete session, in this we need to close session explicitly 
sess = tf.Session()

In [26]:
hello = tf.constant("hello")
world = tf.constant("world")
helloworld = tf.add(hello,world)
sess.run(helloworld)

b'helloworld'

In [27]:
#This is placeholder
a = tf.placeholder(tf.float32)

In [28]:
b=a*2

In [31]:
#sess.run(b , feed_dict={a:3})
#or
sess.run(b,{a:3})

6.0

In [34]:
#feeding a placeholder with vector of rank 1
sess.run(b , feed_dict={a:[3,4,5]})

array([ 6.,  8., 10.], dtype=float32)

In [35]:
#printing the values
result = sess.run(b , feed_dict={a:[3,4,5]})
print(result)

[ 6.  8. 10.]


In [36]:
dictornary = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
result = sess.run(b,feed_dict=dictornary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [37]:
sess.close()